spring:
  application:
    name: stars
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  datasource:
      url: jdbc:mysql://127.0.0.1/stars
      username: root
      password:
      driver-class-name: com.mysql.jdbc.Driver
jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800