spring:
  application:
    name: stars
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800

---

spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://127.0.0.1/stars
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver

---

spring:
  profiles: test
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: